### ISSUE TITLE
No support for non-confidential (native) clients

### ISSUE THREAD

**Issue by Jajcus** [maraujop/requests-oauth2#15]
I have looked at the code and it seems to be impossible to use it without client_secret. No client_secret would be issued for non-confidential clients (like native apps), so this library seems useless for this purpose.

Is that true or am I missing something?

**Comment by rollcat** [comment]
Can you please provide an example service that uses this scheme? I'm more than happy to add support.

**Comment by Jajcus** [comment]
I am building my own service, based on the RFCs available and my requirements. I am not sure what existing, public service support non-confidential client, but I guess there should be some, as non-confidential clients were always part of the OAuth2 specification (though RFC 6749 does not really tell how to use that in a secure and reliable way, RFC 8252 with RFC 7636 do).

I have chosen to use requests-oauthlib for my reference client implementation for now. As much as I hate the oauthlib messy API, it provides the functionality I need.

I am leaving this issue here as a notice about the missing functionality for anyone looking for this. I guess it is not a problem in most use scenarios.

**Comment by rollcat** [comment]
The problem with OAuth2 is every provider takes the liberty to implement the parts they like, how they like it. Facebook is passing tokens around in query strings / request body. Google uses a header. Some providers use a space character to separate scopes, some use a comma. I don't care what the RFC's say, because this is not how the world works. If you tell me which service you want supported, I will write the integration AND example code AND documentation, AND make sure everything is reasonably readable and simple to follow. Writing code to make RFC's happy won't solve any real-world problems (unless you can give me a concrete example as a test case).

If you're still interested, please re-open.
